name: Test

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.11
          uses: actions/setup-python@v5
          with:
            python-version: 3.11

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt -r app/tests/requirements.txt

        - name: Run tests
          run: |
            # TODO: set these variables in a better way
            export BROKER_ORIGIN=https://localhost
            export MTLS_CLIENT_CERT_PATH=/open_banking_eidas_broker/certs/client.crt
            export MTLS_CLIENT_KEY_PATH=/open_banking_eidas_broker/certs/client.key
            export QSEAL_CERT_PATH=/open_banking_eidas_broker/certs/server.crt
            export QSEAL_KEY_NAME=server.key
            export QWAC_CERT_NAME=server.crt
            export QWAC_KEY_NAME=server.key

            pytest app/tests/unit_test.py
